<?php  //[STAMP] a8a71e543f1ff1f4a5e8aacfc168e7f7
namespace _generated\_generated;

// This class was automatically generated by the steppify task
// You should not change it manually as it will be overwritten on next steppify run
// @codingStandardsIgnoreFile

trait Tad\Tests\Modules\ModuleZeroGherkinSteps
{
        
    /**
     * [!] Utility method is generated from steppify task.
     *
     * Converts any TableNode found in an array to an array of associative arrays.
     *
     * @param array $args An array of arguments that should be parsed to convert TableNode
     *              to arrays.
     * @param array $iterations Passed by reference; will be set to empty array if there
     *              there are no TableNode arguments among the arguments, will be set to
     *              an array of function call arguments if found.
     */
    public function _convertTableNodesToArrays(array $args, &$iterations = []) {
        foreach($args as $key => $value) {
            if(is_a($value, 'Behat\Gherkin\Node\TableNode')){
                $rows = $value->getRows();
                $keys = array_shift($rows);
                $array_value = array_map(function(array $row) use ($keys) {
                    return array_combine($keys,$row);
                }, $rows);
                
                $iterations[] = array_replace($args, [$key => $array_value]);
            }
        }
        
        return $args;
    }
    
    
}
